# Generated by Django 5.0 on 2023-12-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='f_name',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
