# Generated by Django 5.0 on 2023-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_students_f_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='f_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
