# Generated by Django 5.0 on 2024-01-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
